server:
  port: 8085
#server.port=8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#--------------------------------------------

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: microservice1
              uri: lb://microservice1  #http://localhost:8082
              predicates:
                - Path=/products/**
            - id: microservice2
              uri: lb://microservice2
              predicates:
                - Path=/orders/**